### ISSUE TITLE
EntitiesControllerTest#test_should_destroy_entity

### ISSUE THREAD

**Issue by Mirv** [banane-io/PDB#61]
``
$  rake test test/controllers

Finished in 19.715514s, 2.1810 runs/s, 3.6519 assertions/s.

  1) Error:
EntitiesControllerTest#test_should_destroy_entity:
ActiveRecord::InvalidForeignKey: ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: update or delete on table "entities" violates foreign key constraint "players_entity_id_fk" on table "players"
  Detail: Key (id)=(1) is still referenced from table "players".: DELETE FROM "entities" WHERE "entities"."id" = 1
    app/controllers/entities_controller.rb:61:in `destroy'
    test/controllers/entities_controller_test.rb:45:in `block in test_should_destroy_entity'
    test/controllers/entities_controller_test.rb:44:in `block in test_should_destroy_entity'
```

**Comment by Mirv** [comment]
Note, I found that `:delete` was being used, doing so is not Rails Way...as it prevents other related callbacks from firing, meaning there's potentially checks that aren't ran when this happens.

**Comment by Mirv** [comment]
inserted

`, dependent: :destroy`

To players, entities & users to honor the foreign keys.

```
EntitiesControllerTest: test_should_destroy_entity
--------------------------------------------------
  Entity Load (1.2ms)  SELECT  "entities".* FROM "entities" WHERE "entities"."id" = 1 LIMIT 1
  User Load (1.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = 135138680 LIMIT 1
   (1.0ms)  SELECT COUNT(*) FROM "entities"
Processing by EntitiesController#destroy as HTML
  Parameters: {"id"=>"1"}
  User Load (1.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = 135138680  ORDER BY "users"."id" ASC LIMIT 1
  Entity Load (1.3ms)  SELECT  "entities".* FROM "entities" WHERE "entities"."id" = 1 LIMIT 1
  Savepoint (0.7ms)  SAVEPOINT active_record_1
  Player Load (8.6ms)  SELECT  "players".* FROM "players" WHERE "players"."entity_id" = 1 LIMIT 1
  User Load (14.3ms)  SELECT  "users".* FROM "users" WHERE "users"."player_id" = 1 LIMIT 1
  SQL (15.9ms)  DELETE FROM "users" WHERE "users"."id" = 135138680
  Savepoint (17.0ms)  ROLLBACK TO SAVEPOINT active_record_1
Completed 500 Internal Server Error in 2752ms (ActiveRecord: 59.4ms)
```

Resulting error summary...

```
Finished in 11.005418s, 0.6361 runs/s, 0.9086 assertions/s.

  1) Error:
EntitiesControllerTest#test_should_destroy_entity:
Java::JavaLang::StackOverflowError: 
   
7 runs, 10 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by Mirv** [comment]
There's a small part of me that believes you are going to have more than one entity on the map/game belonging to a single player & that means you need to have a `has_many` relationship or a `has_many: :through` relationship.

**Comment by Mirv** [comment]
Also, why does the entity HAVE a player?  Why doesn't the player HAVE an entity on the map?

**Comment by Mirv** [comment]
add_foreign_key :identities, :users, on_delete: :cascade

https://stackoverflow.com/questions/29544693/cant-delete-object-due-to-foreign-key-constraint

**Comment by Mirv** [comment]
Oddity:

I noticed there's duplicates in the `schema.rb` on two of the foreign key entries as i'm doing this...that might have been the issue too...

```
  add_foreign_key "entities", "map_points", name: "entities_map_point_id_fk"
  add_foreign_key "entities", "map_points", name: "entities_map_point_id_fk"
  add_foreign_key "players", "entities", name: "players_entity_id_fk"
  add_foreign_key "players", "entities", name: "players_entity_id_fk"
  add_foreign_key "users", "players", name: "users_player_id_fk"
```

**Comment by Mirv** [comment]
duplication watch on rails....not catching these in duplicate?  should rails sort that or should I code dive it to suggest a fix to rails team?

**Comment by Mirv** [comment]
Out put from removing the foreign keys...
```
   (43.4ms)  SELECT version()
  ActiveRecord::SchemaMigration Load (1.8ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Migrating to FixForeignKey (20171017222022)
== 20171017222022 FixForeignKey: migrating ====================================
-- remove_foreign_key("users", "players")
   (3.7ms)  ALTER TABLE "users" DROP CONSTRAINT "users_player_id_fk"
   -> 0.0099s
   -> 0 rows
-- remove_foreign_key("players", "entities")
   (1.1ms)  ALTER TABLE "players" DROP CONSTRAINT "players_entity_id_fk"
   -> 0.0036s
   -> 0 rows
-- remove_foreign_key("entities", "map_points")
   (2.2ms)  ALTER TABLE "entities" DROP CONSTRAINT "entities_map_point_id_fk"
   -> 0.0335s
   -> 0 rows
== 20171017222022 FixForeignKey: migrated (0.0511s) ===========================

  SQL (4.3ms)  INSERT INTO "schema_migrations" ("version") VALUES ('20171017222022')
  ActiveRecord::SchemaMigration Load (0.9ms)  SELECT "schema_migrations".* FROM "schema_migrations"
   (33.5ms)  SELECT t2.oid::regclass::text AS to_table, a1.attname AS column, a2.attname AS primary_key, c.conname AS name, c.confupdtype AS on_update, c.confdeltype AS on_delete FROM pg_constraint c JOIN pg_class t1 ON c.conrelid = t1.oid JOIN pg_class t2 ON c.confrelid = t2.oid JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid JOIN pg_namespace t3 ON c.connamespace = t3.oid WHERE c.contype = 'f'   AND t1.relname = 'entities'   AND t3.nspname = ANY (current_schemas(false)) ORDER BY c.conname 
   (85.1ms)  SELECT t2.oid::regclass::text AS to_table, a1.attname AS column, a2.attname AS primary_key, c.conname AS name, c.confupdtype AS on_update, c.confdeltype AS on_delete FROM pg_constraint c JOIN pg_class t1 ON c.conrelid = t1.oid JOIN pg_class t2 ON c.confrelid = t2.oid JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid JOIN pg_namespace t3 ON c.connamespace = t3.oid WHERE c.contype = 'f'   AND t1.relname = 'identities'   AND t3.nspname = ANY (current_schemas(false)) ORDER BY c.conname 
   (7.6ms)  SELECT t2.oid::regclass::text AS to_table, a1.attname AS column, a2.attname AS primary_key, c.conname AS name, c.confupdtype AS on_update, c.confdeltype AS on_delete FROM pg_constraint c JOIN pg_class t1 ON c.conrelid = t1.oid JOIN pg_class t2 ON c.confrelid = t2.oid JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid JOIN pg_namespace t3 ON c.connamespace = t3.oid WHERE c.contype = 'f'   AND t1.relname = 'map_points'   AND t3.nspname = ANY (current_schemas(false)) ORDER BY c.conname 
   (5.0ms)  SELECT t2.oid::regclass::text AS to_table, a1.attname AS column, a2.attname AS primary_key, c.conname AS name, c.confupdtype AS on_update, c.confdeltype AS on_delete FROM pg_constraint c JOIN pg_class t1 ON c.conrelid = t1.oid JOIN pg_class t2 ON c.confrelid = t2.oid JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid JOIN pg_namespace t3 ON c.connamespace = t3.oid WHERE c.contype = 'f'   AND t1.relname = 'players'   AND t3.nspname = ANY (current_schemas(false)) ORDER BY c.conname 
   (5.4ms)  SELECT t2.oid::regclass::text AS to_table, a1.attname AS column, a2.attname AS primary_key, c.conname AS name, c.confupdtype AS on_update, c.confdeltype AS on_delete FROM pg_constraint c JOIN pg_class t1 ON c.conrelid = t1.oid JOIN pg_class t2 ON c.confrelid = t2.oid JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid JOIN pg_namespace t3 ON c.connamespace = t3.oid WHERE c.contype = 'f'   AND t1.relname = 'terrains'   AND t3.nspname = ANY (current_schemas(false)) ORDER BY c.conname 
   (3.3ms)  SELECT t2.oid::regclass::text AS to_table, a1.attname AS column, a2.attname AS primary_key, c.conname AS name, c.confupdtype AS on_update, c.confdeltype AS on_delete FROM pg_constraint c JOIN pg_class t1 ON c.conrelid = t1.oid JOIN pg_class t2 ON c.confrelid = t2.oid JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid JOIN pg_namespace t3 ON c.connamespace = t3.oid WHERE c.contype = 'f'   AND t1.relname = 'users'   AND t3.nspname = ANY (current_schemas(false)) ORDER BY c.conname 
   (2.9ms)  SELECT t2.oid::regclass::text AS to_table, a1.attname AS column, a2.attname AS primary_key, c.conname AS name, c.confupdtype AS on_update, c.confdeltype AS on_delete FROM pg_constraint c JOIN pg_class t1 ON c.conrelid = t1.oid JOIN pg_class t2 ON c.confrelid = t2.oid JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid JOIN pg_namespace t3 ON c.connamespace = t3.oid WHERE c.contype = 'f'   AND t1.relname = 'entities'   AND t3.nspname = ANY (current_schemas(false)) ORDER BY c.conname 
   (3.0ms)  SELECT t2.oid::regclass::text AS to_table, a1.attname AS column, a2.attname AS primary_key, c.conname AS name, c.confupdtype AS on_update, c.confdeltype AS on_delete FROM pg_constraint c JOIN pg_class t1 ON c.conrelid = t1.oid JOIN pg_class t2 ON c.confrelid = t2.oid JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid JOIN pg_namespace t3 ON c.connamespace = t3.oid WHERE c.contype = 'f'   AND t1.relname = 'identities'   AND t3.nspname = ANY (current_schemas(false)) ORDER BY c.conname 
   (3.2ms)  SELECT t2.oid::regclass::text AS to_table, a1.attname AS column, a2.attname AS primary_key, c.conname AS name, c.confupdtype AS on_update, c.confdeltype AS on_delete FROM pg_constraint c JOIN pg_class t1 ON c.conrelid = t1.oid JOIN pg_class t2 ON c.confrelid = t2.oid JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid JOIN pg_namespace t3 ON c.connamespace = t3.oid WHERE c.contype = 'f'   AND t1.relname = 'map_points'   AND t3.nspname = ANY (current_schemas(false)) ORDER BY c.conname 
   (2.9ms)  SELECT t2.oid::regclass::text AS to_table, a1.attname AS column, a2.attname AS primary_key, c.conname AS name, c.confupdtype AS on_update, c.confdeltype AS on_delete FROM pg_constraint c JOIN pg_class t1 ON c.conrelid = t1.oid JOIN pg_class t2 ON c.confrelid = t2.oid JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid JOIN pg_namespace t3 ON c.connamespace = t3.oid WHERE c.contype = 'f'   AND t1.relname = 'players'   AND t3.nspname = ANY (current_schemas(false)) ORDER BY c.conname 
   (3.4ms)  SELECT t2.oid::regclass::text AS to_table, a1.attname AS column, a2.attname AS primary_key, c.conname AS name, c.confupdtype AS on_update, c.confdeltype AS on_delete FROM pg_constraint c JOIN pg_class t1 ON c.conrelid = t1.oid JOIN pg_class t2 ON c.confrelid = t2.oid JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid JOIN pg_namespace t3 ON c.connamespace = t3.oid WHERE c.contype = 'f'   AND t1.relname = 'terrains'   AND t3.nspname = ANY (current_schemas(false)) ORDER BY c.conname 
   (3.1ms)  SELECT t2.oid::regclass::text AS to_table, a1.attname AS column, a2.attname AS primary_key, c.conname AS name, c.confupdtype AS on_update, c.confdeltype AS on_delete FROM pg_constraint c JOIN pg_class t1 ON c.conrelid = t1.oid JOIN pg_class t2 ON c.confrelid = t2.oid JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid JOIN pg_namespace t3 ON c.connamespace = t3.oid WHERE c.contype = 'f'   AND t1.relname = 'users'   AND t3.nspname = ANY (current_schemas(false)) ORDER BY c.conname 
```

**Comment by Mirv** [comment]
The stackoverflow error.... It's a bug in the interpreter, but often caused by adverse circumstances that would kill the program anyhow. You're supposed to always get a nice Ruby stack trace. If you get a segfault instead, it's a bug.

**Comment by Mirv** [comment]
The foreign key still isn't reflecting on this

```

pdb_development=# \d+ entities
                                                          Table "public.entities"
    Column    |            Type             |                       Modifiers                       | Storage  | Stats target | Description 
--------------+-----------------------------+-------------------------------------------------------+----------+--------------+-------------
 id           | integer                     | not null default nextval('entities_id_seq'::regclass) | plain    |              | 
 name         | character varying           |                                                       | extended |              | 
 description  | character varying           |                                                       | extended |              | 
 map_point_id | integer                     |                                                       | plain    |              | 
 created_at   | timestamp without time zone |                                                       | plain    |              | 
 updated_at   | timestamp without time zone |                                                       | plain    |              | 
Indexes:
    "entities_pkey" PRIMARY KEY, btree (id)
    "index_entities_on_map_point_id" btree (map_point_id)
    "index_entities_on_map_point_id_and_created_at" btree (map_point_id, created_at)
Foreign-key constraints:
    "entities_map_point_id_fk" FOREIGN KEY (map_point_id) REFERENCES map_points(id)
Referenced by:
    TABLE "players" CONSTRAINT "players_entity_id_fk" FOREIGN KEY (entity_id) REFERENCES entities(id)
Has OIDs: no

```

**Comment by Mirv** [comment]
```
  create_table "entities", force: :cascade do |t|
    t.string   "name"
    t.string   "description"
    t.integer  "map_point_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "entities", ["map_point_id", "created_at"], name: "index_entities_on_map_point_id_and_created_at", using: :btree
  add_index "entities", ["map_point_id"], name: "index_entities_on_map_point_id", using: :btree
```

**Comment by Mirv** [comment]
So just describing the problem in terms of a theoretical game ...

- entities exist on a map

In terms of rails / AR relationships ...

- so a map has entities
- entities belong to a map 

```
class MapPoint < ActiveRecord::Base
  has_many :entities

class Entity < ActiveRecord::Base
  belongs_to :map_point
```

**Comment by marcandregirard** [comment]
Since I moved away from Ruby and Rails, I'll be closing this issue since it's not relevant anymore.
